version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: orders
      - name: order_items
      - name: payments
      - name: reviews
      - name: customers
      - name: products
      - name: sellers
		