version: 2

models:

  - name: fct_order_items
    description: "Atomic fact table at order-item grain"

    columns:

      - name: order_item_sk
        description: "Deterministic surrogate key for order-item"
        tests:
          - not_null
          - unique

      - name: order_id
        description: "Order business key"
        tests:
          - not_null

      - name: order_item_id
        description: "Item number within order"
        tests:
          - not_null

      - name: product_id
        description: "Foreign key to dim_product"
        tests:
          - not_null
          - relationships:
              to: ref('dim_product')
              field: product_id

      - name: customer_id
        description: "Foreign key to dim_customer"
        tests:
          - not_null
          - relationships:
              to: ref('dim_customer')
              field: customer_id

      - name: seller_id
        description: "Foreign key to dim_seller"
        tests:
          - not_null
          - relationships:
              to: ref('dim_seller')
              field: seller_id


  - name: fct_orders
    description: "Aggregated fact table at order grain"

    columns:
      - name: order_id
        tests:
          - not_null
          - unique


  - name: dim_customer
    description: "Customer dimension"

    columns:
      - name: customer_id
        tests:
          - not_null
          - unique


  - name: dim_product
    description: "Product dimension"

    columns:
      - name: product_id
        tests:
          - not_null
          - unique


  - name: dim_seller
    description: "Seller dimension"

    columns:
      - name: seller_id
        tests:
          - not_null
          - unique


  - name: dim_date
    description: "Date dimension derived from orders"

    columns:
      - name: date_day
        tests:
          - not_null
          - unique